<?php
namespace GGG\Bundle\ODataBundle\Repository;

require_once __DIR__ . '/../Model/Entities.php';

use Symfony\Component\DependencyInjection\ContainerAware;

/**
 * OData
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 * @Annotation
 */
class Entities extends ContainerAware
{
    /**
     * @return mixed
     * @throws \DataServiceRequestException
     */
    public function getEntities()
    {
        $cache = $this->container->get('doctrine_cache.providers.sylius_settings');
        $cache->setNamespace('OData');
        $proxy = new \NorthwindEntities();
        if ($cache->contains('customer')) {
            $customer = $cache->fetch('customer');
        } else {
            $response = $proxy->Execute("Customers('ALFKI')");
            $customer = $response->Result[0];
            $cache->save('customer', $customer);
        }
        return $customer;
    }

}
