<?php

namespace GGG\Bundle\BpmnBundle\Doctrine\ORM;

use Doctrine\ORM\EntityRepository;
use GGG\Bundle\BpmnBundle\Repository\BpmnRepositoryInterface;

/**
 * Bpmn
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Bpmn extends EntityRepository implements BpmnRepositoryInterface
{
}
