ggg_bpmn_history_all:
    pattern:  /history
    defaults: { _controller: GGGBpmnBundle:History:all, _format: ~ }
    requirements:
        _method: GET

ggg_bpmn_history_get:
    pattern:  /history/{id}
    defaults: { _controller: GGGBpmnBundle:History:get, _format: ~ }
    requirements:
        _method: GET
        id: "\d+"
